### ISSUE TITLE
Mfxh264enc crashed

### ISSUE THREAD

**Issue by topilski** [01org/gstreamer-media-SDK#20]
Hi stacktrace is:

```
Thread 8 "udb_conn_video_" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffddf72700 (LWP 11052)]
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-16.fc24.x86_64 bzip2-libs-1.0.6-21.fc25.x86_64 cairo-1.14.8-1.fc25.x86_64 dbus-glib-0.108-1.fc25.x86_64 dbus-libs-1.11.12-1.fc25.x86_64 dconf-0.26.0-1.fc25.x86_64 expat-2.2.0-1.fc25.x86_64 fontconfig-2.12.1-1.fc25.x86_64 freetype-2.6.5-9.fc25.x86_64 glib-networking-2.50.0-1.fc25.x86_64 glib2-2.50.3-1.fc25.x86_64 gmp-6.1.1-1.fc25.x86_64 gnutls-3.5.12-2.fc25.x86_64 js-1.8.5-25.fc25.x86_64 keyutils-libs-1.5.9-8.fc24.x86_64 krb5-libs-1.14.4-7.fc25.x86_64 libX11-1.6.5-1.fc25.x86_64 libXau-1.0.8-6.fc24.x86_64 libXext-1.3.3-4.fc24.x86_64 libXfixes-5.0.3-1.fc25.x86_64 libXrender-0.9.10-1.fc25.x86_64 libblkid-2.28.2-2.fc25.x86_64 libcap-2.25-2.fc25.x86_64 libcom_err-1.43.3-1.fc25.x86_64 libdrm-2.4.81-1.fc25.x86_64 libffi-3.1-9.fc24.x86_64 libgcc-6.3.1-1.fc25.x86_64 libgcrypt-1.6.6-1.fc25.x86_64 libglvnd-0.2.999-14.20170308git8e6e102.fc25.x86_64 libglvnd-egl-0.2.999-14.20170308git8e6e102.fc25.x86_64 libglvnd-glx-0.2.999-14.20170308git8e6e102.fc25.x86_64 libgpg-error-1.24-1.fc25.x86_64 libidn2-2.0.2-1.fc25.x86_64 libmodman-2.0.1-12.fc24.x86_64 libmount-2.28.2-2.fc25.x86_64 libpciaccess-0.13.4-3.fc24.x86_64 libpng-1.6.27-1.fc25.x86_64 libproxy-0.4.14-1.fc25.x86_64 libproxy-mozjs-0.4.14-1.fc25.x86_64 libselinux-2.5-13.fc25.x86_64 libsoup-2.56.0-2.fc25.x86_64 libstdc++-6.3.1-1.fc25.x86_64 libtasn1-4.12-1.fc25.x86_64 libunistring-0.9.4-3.fc24.x86_64 libuuid-2.28.2-2.fc25.x86_64 libva-1.7.3-3.fc25.x86_64 libwayland-client-1.12.0-1.fc25.x86_64 libwayland-cursor-1.12.0-1.fc25.x86_64 libxcb-1.12-1.fc25.x86_64 libxml2-2.9.4-2.fc25.x86_64 lz4-1.7.5-1.fc25.x86_64 mesa-libwayland-egl-17.0.5-2.fc25.x86_64 nettle-3.3-1.fc25.x86_64 nspr-4.14.0-2.fc25.x86_64 openssl-libs-1.0.2k-1.fc25.x86_64 p11-kit-0.23.2-4.fc25.x86_64 pcre-8.40-7.fc25.x86_64 pixman-0.34.0-2.fc24.x86_64 sqlite-libs-3.14.2-1.fc25.x86_64 systemd-libs-231-15.fc25.x86_64 xz-libs-5.2.2-2.fc24.x86_64 zlib-1.2.8-10.fc24.x86_64

```

```
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007fffe05f67ca in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#2  0x00007fffe05f688d in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#3  0x00007fffe0637a0a in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#4  0x00007fffe0637c01 in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#5  0x00007fffe0638d56 in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#6  0x00007fffe8b94ca4 in vaCreateContext () at /lib64/libva.so.1
#7  0x00007fff633741db in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#8  0x00007fff633742ae in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#9  0x00007fff634ad3f9 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#10 0x00007fff634b949a in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#11 0x00007fff634afcf3 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#12 0x00007fff634afec8 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#13 0x00007fff634b11e6 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#14 0x00007fff6336004f in MFXVideoVPP_Query () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#15 0x00007fffe923ca54 in configure_filters () at /usr/local/lib/gstreamer-1.0/libgstmfx.so
#16 0x00007fffe923d07b in gst_mfx_filter_prepare () at /usr/local/lib/gstreamer-1.0/libgstmfx.so
#17 0x00007fffe924d8fc in gst_mfx_encoder_start () at /usr/local/lib/gstreamer-1.0/libgstmfx.so
#18 0x00007fffe9239275 in gst_mfxenc_set_format () at /usr/local/lib/gstreamer-1.0/libgstmfx.so
#19 0x00007fffe96c6156 in gst_video_encoder_setcaps (caps=0x82f590, encoder=0x9c49f0) at gstvideoencoder.c:617
#20 0x00007fffe96c6156 in gst_video_encoder_sink_event_default (encoder=0x9c49f0, event=0x7fffc00062b0) at gstvideoencoder.c:969
#21 0x00007ffff6e3ff77 in gst_pad_send_event_unchecked (pad=pad@entry=0x9c1480, event=event@entry=0x7fffc00062b0, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5607
#22 0x00007ffff6e4040e in gst_pad_push_event_unchecked (pad=pad@entry=0x9c1240, event=0x7fffc00062b0, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5263
#23 0x00007ffff6e40810 in push_sticky (pad=pad@entry=0x9c1240, ev=ev@entry=0x7fffddf71780, user_data=user_data@entry=0x7fffddf717e0) at gstpad.c:3806
#24 0x00007ffff6e3e507 in events_foreach (pad=pad@entry=0x9c1240, func=func@entry=0x7ffff6e406c0 <push_sticky>, user_data=user_data@entry=0x7fffddf717e0) at gstpad.c:603
#25 0x00007ffff6e4aaa1 in check_sticky (event=0x7fffc00062b0, pad=0x9c1240) at gstpad.c:3863
#26 0x00007ffff6e4aaa1 in gst_pad_push_event (pad=pad@entry=0x9c1240, event=0x7fffc00062b0) at gstpad.c:5394
#27 0x00007ffff3c1a676 in gst_pad_set_caps (caps=0x82f590, pad=0x9c1240) at ../../../gst/gstcompat.h:58
#28 0x00007ffff3c1a676 in gst_base_transform_setcaps (trans=trans@entry=0x9e6330, pad=<optimized out>, incaps=<optimized out>) at gstbasetransform.c:1390
#29 0x00007ffff3c1baad in gst_base_transform_sink_eventfunc (trans=0x9e6330, event=0x7fff84002d90) at gstbasetransform.c:1946
#30 0x00007ffff6e3ff77 in gst_pad_send_event_unchecked (pad=pad@entry=0x9c1000, event=event@entry=0x7fff84002d90, type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5607
#31 0x00007ffff6e4040e in gst_pad_push_event_unchecked (pad=pad@entry=0x9c0dc0, event=0x7fff84002d90, type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5263
#32 0x00007ffff6e40810 in push_sticky (pad=pad@entry=0x9c0dc0, ev=ev@entry=0x7fffddf71ad0, user_data=user_data@entry=0x7fffddf71b30) at gstpad.c:3806
#33 0x00007ffff6e3e507 in events_foreach (pad=pad@entry=0x9c0dc0, func=func@entry=0x7ffff6e406c0 <push_sticky>, user_data=user_data@entry=0x7fffddf71b30) at gstpad.c:603
#34 0x00007ffff6e4aaa1 in check_sticky (event=0x7fff84002d90, pad=0x9c0dc0) at gstpad.c:3863
#35 0x00007ffff6e4aaa1 in gst_pad_push_event (pad=0x9c0dc0, event=event@entry=0x7fff84002d90) at gstpad.c:5394
#36 0x00007fffea055408 in gst_queue_push_one (queue=0x9dc0f0) at gstqueue.c:1434
#37 0x00007fffea055408 in gst_queue_loop (pad=<optimized out>) at gstqueue.c:1512
#38 0x00007ffff6e74b11 in gst_task_func (task=0x9d3830) at gsttask.c:334
#39 0x00007ffff73c758e in g_thread_pool_thread_proxy () at /lib64/libglib-2.0.so.0
#40 0x00007ffff73c6b93 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#41 0x00007ffff7bc06ca in start_thread () at /lib64/libpthread.so.0
#42 0x00007ffff5043f7f in clone () at /lib64/libc.so.6
```

libva output:

```
libva info: VA-API version 0.99.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.99 (libva 1.67.0.pre1)
vainfo: Driver version: 16.5.1.59511-ubit
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: <unknown entrypoint>
      VAProfileH264ConstrainedBaseline: <unknown entrypoint>
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : <unknown entrypoint>
      VAProfileH264Main               : <unknown entrypoint>
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : <unknown entrypoint>
      VAProfileH264High               : <unknown entrypoint>
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : <unknown entrypoint>
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileVP9Profile0            : <unknown entrypoint>
      <unknown profile>               : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : <unknown entrypoint>

```

**Comment by ishmael1985** [comment]
Noted, we want to know, is this possibly a regression? For testing purposes can you pull an earlier release from 01.org or from my repo for now and let me know what you get?

https://github.com/ishmael1985/gstreamer-media-SDK

If it is, this regression will be fixed in the 01.org branch.

**Comment by topilski** [comment]
After linux patch updates not reproduced.

**Comment by shailesh83** [comment]
Hi @topilski ,
 
  After linux patch updates not reproduced ? Please can you tell me which linux version you where there and which patch fixed it.

**Comment by topilski** [comment]
Hi @shailesh83 , not interesting anymore.

**Comment by shailesh83** [comment]
@topilski  We are facing similar issue now  with same BackTrace any input would have been helpful.

**Comment by brmarkus** [comment]
Excuse me, Shailesh...
You cannot compare two back-traces without debug-infos, not showing any method names, not showing any parameter values - just based on the number on unresolved calls on the stack...??!

The back-trace from above:
`#0  0x0000000000000000 in  ()
#1  0x00007fffe05f67ca in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#2  0x00007fffe05f688d in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#3  0x00007fffe0637a0a in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#4  0x00007fffe0637c01 in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#5  0x00007fffe0638d56 in  () at /opt/intel/mediasdk/lib64/iHD_drv_video.so
#6  0x00007fffe8b94ca4 in vaCreateContext () at /lib64/libva.so.1
#7  0x00007fff633741db in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#8  0x00007fff633742ae in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#9  0x00007fff634ad3f9 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#10 0x00007fff634b949a in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#11 0x00007fff634afcf3 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#12 0x00007fff634afec8 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#13 0x00007fff634b11e6 in  () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
#14 0x00007fff6336004f in MFXVideoVPP_Query () at /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.21
`
and the back-trace you are referring to:
`#0  0x0000000000000000 in ?? ()
#1  0x00007f92e3f94996 in ?? () from /usr/lib/dri/i965_drv_video.so
#2  0x00007f92e3f94a91 in ?? () from /usr/lib/dri/i965_drv_video.so
#3  0x00007f92e3fe23fa in ?? () from /usr/lib/dri/i965_drv_video.so
#4  0x00007f92e2718908 in vaCreateContext (dpy=0x7f93186ac080, config_id=2049, picture_width=352, picture_height=288, flag=1, render_targets=0x0, num_render_targets=0, context=0x7f931818c394) at /usr/src/debug/libva/16.7.4-r0/git/va/va.c:1021
#5  0x00007f92e1141961 in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#6  0x00007f92e1141a2e in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#7  0x00007f92e12f2e89 in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#8  0x00007f92e13011aa in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#9  0x00007f92e12f5b23 in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#10 0x00007f92e12f6003 in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#11 0x00007f92e12f710c in ?? () from /usr/lib/libmfxhw64-p.so.1.24
#12 0x00007f92e1126b6f in MFXVideoVPP_Query () from /usr/lib/libmfxhw64-p.so.1.24
`
You really treat these "same BackTrace"?
